questions = [
    "Encontre o maior inteiro n tal que 2^n divide (100!)!",
    "Quantas soluções inteiras positivas tem a equação x^4 + y^4 + z^4 = w^4 para w ≤ 100?",
    "Determine o número de maneiras de colorir os vértices de um dodecaedro regular com 3 cores, considerando rotações como equivalentes",
    "Calcule a soma dos divisores de 2^30 * 3^20 * 5^10 que são quadrados perfeitos",
    "Encontre o menor inteiro positivo n tal que φ(n) = 2^10 * 3^5, onde φ é a função de Euler",
    "Quantos números primos p existem tais que p^2 + 2 também é primo e p < 1000?",
    "Determine o coeficiente de x^50 na expansão de (1 + x + x^2 + ... + x^10)^10",
    "Calcule o determinante da matriz 100×100 onde a_{ij} = gcd(i,j)",
    "Encontre o número de soluções inteiras de x^3 + y^3 + z^3 = 33",
    "Determine quantos grafos conexos não-isomorfos existem com exatamente 10 vértices e 15 arestas",
    "Calcule o resto da divisão de 7^(7^7) por 1000",
    "Encontre o maior valor de k tal que existem k inteiros positivos distintos cuja soma dos recíprocos é 1",
    "Determine o número de sequências de 20 elementos usando {1,2,3} onde nenhum elemento aparece 3 vezes consecutivas",
    "Calcule a soma de todos os números de 4 dígitos que são iguais à soma dos cubos de seus dígitos",
    "Encontre o número de maneiras de particionar o conjunto {1,2,3,...,20} em subconjuntos não-vazios de tamanhos iguais",
    "Determine quantos inteiros positivos n ≤ 10000 satisfazem σ(n) = 2n + 1, onde σ é a função soma dos divisores",
    "Calcule o número de soluções inteiras não-negativas de x₁ + x₂ + ... + x₁₀ = 100 com xᵢ ≤ 15 para todo i",
    "Encontre o menor inteiro positivo n tal que n! termina com exatamente 100 zeros",
    "Determine o número de permutações de {1,2,...,15} onde nenhum elemento está em sua posição original",
    "Calcule a soma dos quadrados de todos os divisores de 2^12 * 3^8 * 5^6",
    "Encontre quantas soluções inteiras tem o sistema: x + y + z = 0, x² + y² + z² = 14, xyz = -6",
    "Determine o coeficiente de x^100 y^100 z^100 na expansão de (x + y + z + 1/x + 1/y + 1/z)^300",
    "Calcule o número de subconjuntos de {1,2,3,...,50} cuja soma dos elementos é divisível por 7",
    "Encontre o maior inteiro n tal que 2^n ≤ Σ(k=1 até n) k^k",
    "Determine quantos números triangulares T_n = n(n+1)/2 são também números pentagonais P_m = m(3m-1)/2",
    "Calcule o resto da divisão de Fibonacci(10^6) por 10^9 + 7",
    "Encontre o número de soluções inteiras de |x| + |y| + |z| = 10",
    "Determine quantos polinômios mônicos de grau 5 com coeficientes em {0,1,2} têm todas as raízes reais",
    "Calcule o número de caminhos mais curtos de (0,0) para (20,20) que passam pelo ponto (10,15)",
    "Encontre a maior potência de 3 que divide C(3000,1000), onde C(n,k) é o coeficiente binomial"
]